apiVersion: v1
kind: Service
metadata:
  name: {{ template "openldap.fullname" . }}-headless-slave
  labels:
    app: {{ template "openldap.fullname" . }}-slave
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - port: {{ .Values.service.ldapPort }}
    name: ldap-port
    targetPort: ldap-port
  {{- if .Values.monitoring.enabled }}
  - port: {{ .Values.monitoring.port }}
    name: metrics
    targetPort: metrics
  {{- end }}
  clusterIP: None
  selector:
    app: {{ template "openldap.fullname" . }}-slave
    release: {{ .Release.Name }}
  type: ClusterIP
  sessionAffinity: None
